### ISSUE TITLE
watir 4.+ and firefox profile

### ISSUE THREAD

**Issue by systestrjr** [watir/watir_meta#10]
We have moved away from watir-webdriver(IE) to watir-classic (we found it to be faster and more 'forgiveable' when searching from elements...(atleast on win7-64bit IE9).

So we decided to move to watir 4.+ (to take advantage of the automatic 'require switching'), so now our common scripts are now working on IE, BUT I cant seem to get firefox to load the customized profile... (1 example use of profile attached below)

I google'd but couldnt find an example that uses the watir 4.0 with firefox profile. Please help.

C:>ruby -v

ruby 1.9.3p385 (2013-02-06) [i386-mingw32]

C:>gem list | grep 'watir'

commonwatir (4.0.0)

watir (4.0.2 x86-mingw32)

watir-classic (3.7.0)

watir-webdriver (0.6.4)

C:>irb

irb(main):001:0> require 'watir'

=> true

irb(main):002:0> profile = Selenium::WebDriver::Firefox::Profile.new

```
NameError: uninitialized constant Selenium

from (irb):2

from C:/Ruby193/bin/irb:12:in `<main>'
```

irb(main):003:0> ^C

irb(main):003:0>

Terminate batch job (Y/N)? Y

C:>irb

irb(main):001:0> require 'watir-webdriver'

=> true

irb(main):002:0> profile = Selenium::WebDriver::Firefox::Profile.new

=> #

irb(main):003:0> profile['network.http.phishy-userpass-length'] = 255

=> 255

irb(main):004:0> driver = Selenium::WebDriver.for(:firefox, :profile => profile)

=> #

irb(main):005:0> browser = Watir::Browser.new(driver)

=> #

irb(main):006:0> ^C

irb(main):006:0> Terminate batch job (Y/N)? Y

**Comment by jarmo** [comment]
If you're using firefox, then in the end Watir-WebDriver is used. You have to load selenium-webdriver to create the profile and this is how you open up the browser:

``` ruby
require "watir"
require "selenium-webdriver" # load this only when going to use webdriver

browser = Watir::Browser.new :firefox, :profile => Selenium::WebDriver::Firefox::Profile.new
```

Watir-Classic drives only IE.

Closing this issue, since it is not a bug.
