### ISSUE TITLE
Cannot use headless: Stack too deep

### ISSUE THREAD

**Issue by phuongnd08** [watir/watir_meta#13]
I installed headless gem.
When I try: Watir::Browser.new :headless, I get: Stack too deep.

**Comment by zeljkofilipin** [comment]
You should not start a headless browser, you should start a normal browser but in a headless mode. Take a look at the documentation (from http://watirwebdriver.com/headless/):

``` ruby
require 'watir-webdriver'
require 'headless'
headless = Headless.new
headless.start
b = Watir::Browser.start 'www.google.com'
puts b.title
b.close
headless.destroy
```

**Comment by zeljkofilipin** [comment]
I have wrote some documentation on headless testing:

https://github.com/watir/watirbook/blob/master/main/headless.md

**Comment by phuongnd08** [comment]
It turned out to be an issue with zeus. I later run rails without zeus and can start a headless browser with `Water::Browser.new :phantomjs`

Anyway, many thanks for your follow up :+1:

**Comment by JuPlutonic** [comment]
404, above link to headless.md.
Now it's located [right here.](https://github.com/watir/watirbook/blob/master/manuscript/main/headless.md)
