### ISSUE TITLE
Update the HTML elements supported by Watir page

### ISSUE THREAD

**Issue by dare05** [watir/watir_meta#14]
https://github.com/watir/watir/wiki/HTML-Elements-Supported-by-Watir you should update it with textarea, because of the warning issued when I use text_field for textarea elements:

Locating textareas with '#text_field' is deprecated. Please, use '#textarea' method instead.

**Comment by zeljkofilipin** [comment]
Thanks for letting us know. Do you know that page is a wiki page, meaning you can edit it yourself? It  is probably easier to fix it than to report it is broken. :smile: Let me know if you would like to fix the page yourself, but you need help with that.

**Comment by dare05** [comment]
Assuming all things that apply to text_field apply to textarea as well, did an edit. Let me know if all is good :)

**Comment by zeljkofilipin** [comment]
Looks good to me! Thanks! :thumbsup: Should this issue be closed then?

**Comment by dare05** [comment]
yep.
