### ISSUE TITLE
Errors not showing up on Command line prompt any more

### ISSUE THREAD

**Issue by qawatirqns** [watir/watir_meta#15]
Hi,
  I used to see errors on command line prompt when I run .rb file which would help me in fixing the errors, recently They don't show up any more .
Not sure what to do to make them show the errors again .
Any help is appreciated.

**Comment by zeljkofilipin** [comment]
You will have to provide more information:
- Are you using watir-classic or watir-webdriver?
- The last version where you still see errors.
- Sample file that would cause an error.
- Console output showing the error.
- Ruby version would also help.

**Comment by zeljkofilipin** [comment]
Closing, no reply in 10 days.
