### ISSUE TITLE
Can I run watir on Debian server in production&

### ISSUE THREAD

**Issue by stopanko** [watir/watir_meta#18]
I have some parser controller. It using watir
`class ParserController < ApplicationController`
`require 'open-uri''`
  `require 'nokogiri''`
 `require 'watir''`
 `'require 'selenium/webdriver''`
 `' def parse'`
  `' car_brands_count = CarBrand.count.to_i.to_i'`
  `' @output = Array.new'`
  `' browser = Watir::Browser.new'`
   `'browser.goto "http://www.site.ru/"'`

How rune this action with Watir in production with Debian server?

**Comment by p0deje** [comment]
You should only report bugs here. If you want to ask a question on watir, use [watir google group](https://groups.google.com/forum/#!forum/watir-general) [stackoverflow](http://stackoverflow.com)
