### ISSUE TITLE
Deploying watir with phantomJS webdriver on heroku

### ISSUE THREAD

**Issue by davidgeismar** [watir/watir_meta#20]
I am using gem Watir with  a ghostdriver using phantomJS as is explained here : http://watirmelon.com/2013/02/05/watir-webdriver-with-ghostdriver-on-osx-headless-browser-testing/ 

This works perfectly locally, however when I try using it in production after heroku deploy I get the following error:
 `Selenium::WebDriver::Error::WebDriverError (Unable to find phantomjs executable.).`
So I tried to add nodeJS & phantomJS buildpack to my project. I now have all these buildpacks installed
 `tennis-match git:(master) heroku buildpacks --app we-tennis-staging
=== we-tennis-staging Buildpack URLs
1. https://github.com/heroku/heroku-buildpack-ruby
2. http://github.com/stomita/heroku-buildpack-phantomjs.git
3. https://github.com/ddollar/heroku-buildpack-multi.git
4. https://github.com/heroku/heroku-buildpack-nodejs.git
5. --buildpack=https://github.com/ddollar/heroku-buildpack-multi.git`

But I get this error when trying to deploy : 

`remote: -----> Fetching custom git buildpack... done
remote: -----> PhantomJS app detected
remote: -----> Fetching PhantomJS 1.9.8 binaries at https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
remote: -----> Extracting PhantomJS 1.9.8 binaries to /tmp/build_d85248ffdc50138a22fb863a0367b5f2/vendor/phantomjs
remote: -----> exporting PATH and LIBRARY_PATH
remote: -----> Fetching custom git buildpack... done
remote: 
remote:  !     Push rejected, failed to detect
remote: 
remote: Verifying deploy...
remote: 
remote: !   Push rejected to we-tennis-staging.
remote:`

Is it possible to make Watir&phantomJS working with heroku ?

**Comment by p0deje** [comment]
That is an bug tracker for Watir project. Please post your question to [watir-general](https://groups.google.com/forum/#!forum/watir-general) mailing list.
