### ISSUE TITLE
using watir with jenkins

### ISSUE THREAD

**Issue by caio1234** [watir/watir_meta#23]
Can I use watir in jenkins machines?

**Comment by cpanato** [comment]
yes

**Comment by tbutiu** [comment]
of course. Jenkins runs your watir scripts, as a job.

**Comment by caio1234** [comment]
thanks

**Comment by p0deje** [comment]
This is not a bug, but a question. Please post questions to [watir-general](https://groups.google.com/d/forum/watir-general) mailing list.
