### ISSUE TITLE
watir 1.5.3 is not clicking links on IE9

### ISSUE THREAD

**Issue by shanth** [watir/watir_meta#3]
watir 1.5.3 is not clicking links on IE9.The same scripts are working fine on IE8 and IE9 with compability veiw toggle on.
Any workaround to run the same scripts on IE9 without toggle on compability veiw.
OS:Windows 7 SP1 32bit

**Comment by jarmo** [comment]
Try newest watir-classic to see if it works for you. I don't have any problems using IE9 with watir. Closing for now.
