### ISSUE TITLE
rautomation dependency missing in gem

### ISSUE THREAD

**Issue by brettveenstra** [watir/watir_meta#4]
Just installed watir and tried sending Function Key (e.g. browser.send_keys :f9) and got an error stating the key combination was not supported.

This blew up in the rautomation library.  Once I installed the rautomation gem, I can now use the send_keys for :f9.

Could you please update the dependencies for this gem to include rautomation with the Function-key support?

Thanks!

**Comment by jarmo** [comment]
Watir-classic has a dependency for RAutomation set properly. Like this:

```
'rautomation', '~>0.7.2'
```

I'm not sure if that was not the case ~3 months ago. Closing.
