### ISSUE TITLE
Driver library needs to be loaded before executing any of the real methods.

### ISSUE THREAD

**Issue by jarmo** [watir/watir_meta#5]
Problem with current solution is that for example `#start`, `#attach` and any other Watir class methods are not accessible because watir-webdriver or watir-classic is loaded in `#new`. It seems that the loading should be done by `#method_missing` or by any other means to fix these problems.

**Comment by jarmo** [comment]
Fixed in https://github.com/watir/watir/commit/43d3b6341d22956789e809dfeca421a7a0d96e0f and in version 4.0.1.

**Comment by niartseoj** [comment]
I'm observing similar behavior using 
gems/watir-classic-4.1.0/lib/watir-classic/browser.rb:116:in `method_missing': (in OLE method`Windows': ) (WIN32OLERuntimeError)

require 'watir-classic'
b = Watir::Browser.attach(:title, //)

same with require 'watir'
