### ISSUE TITLE
click_no_wait giving error when launching modal dialogs

### ISSUE THREAD

**Issue by camcknight** [watir/watir_meta#8]
I am updating from watir 1.9.1 to watir 4, using watir classic 3.6.0
When I try and execute a click_no_wait on link that executes a javascript function and pulls up a modal dialog I get the following error: 
I have tried a couple of things to try and get around it, but all of them end up giving me the same error.

```
NoMethodError: undefined method `join' for nil:NilClass
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/watir-classic-3.6.0/lib/watir-classic/element.rb:453:in `generate_ruby_code'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/watir-classic-3.6.0/lib/watir-classic/element.rb:296:in `block in method_missing'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/watir-classic-3.6.0/lib/watir-classic/element.rb:477:in `perform_action'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/watir-classic-3.6.0/lib/watir-classic/element.rb:295:in `method_missing'
```

**Comment by jarmo** [comment]
What is the code you're using to perform that click?

**Comment by camcknight** [comment]
The exact code is:

```
@browser.frame(:id, 'MainFrame').table(:id, /tblDynamicMenu/).cell(:text, 'SLR').click_no_wait
```

Clicking on this cell fires a javascript function that does some back ground calculations/checks and then prompts with a modal dialog with context depending on how the calculations come back .
I have tried to fire the javascript event and the same errors are returned.

**Comment by jarmo** [comment]
Can you try to use `td` instead of `cell`:

```
@browser.frame(:id, 'MainFrame').table(:id, /tblDynamicMenu/).td(:text, 'SLR').click_no_wait
```

If that also gives out an error then try these lines to see where it goes wrong:

```
@browser.frame(:id, 'MainFrame').table(:id, /tblDynamicMenu/).click_no_wait
@browser.frame(:id, 'MainFrame').click_no_wait
```

**Comment by camcknight** [comment]
Using td/tr seem to do the trick. 
I thought I had already tried that, when I made this post, apparently not. 
Thanks.
